// ─────────────────────────────────────────────────────────────────────────────
// firebase_uploader.js
//
// Handles Firebase Admin SDK initialization and uploading extracted match data
// to Firestore. Each match is written as a separate document under:
//   vfootball_results/{gameId}_{league}
//
// Requires: serviceAccountKey.json in the server directory (generated by
// Firebase Console → Project Settings → Service Accounts → Generate new key)
// ─────────────────────────────────────────────────────────────────────────────

const admin = require('firebase-admin');
const path = require('path');
const fs = require('fs');

let db = null;

function initFirebase() {
    if (admin.apps.length > 0) {
        console.log('[Firebase] Already initialized. Reusing existing app.');
        db = admin.firestore();
        return true;
    }

    const keyPath = path.join(__dirname, 'serviceAccountKey.json');
    if (!fs.existsSync(keyPath)) {
        console.error('[Firebase] ❌ serviceAccountKey.json not found at:', keyPath);
        console.error('[Firebase] ➡️  Go to: Firebase Console → Project Settings → Service Accounts → Generate new key');
        return false;
    }

    try {
        const serviceAccount = require(keyPath);
        admin.initializeApp({
            credential: admin.credential.cert(serviceAccount),
        });
        db = admin.firestore();
        console.log('[Firebase] ✅ Firebase Admin SDK initialized successfully.');
        return true;
    } catch (err) {
        console.error('[Firebase] ❌ Failed to initialize Firebase Admin SDK:', err.message);
        return false;
    }
}

/**
 * Uploads an array of match objects to the Firestore collection `vfootball_results`.
 * Uses a batch write for efficiency. Each document ID is unique: `${gameId}_${league}`.
 * Already-existing documents are MERGED (not overwritten) to protect existing data.
 *
 * @param {Array} matches - Array of match objects from gemini_extractor
 * @param {Function} onProgress - Callback(message) for real-time status updates
 * @returns {{ uploaded: number, skipped: number }}
 */
async function uploadMatchesToFirebase(matches, onProgress = () => {}) {
    if (!initFirebase()) {
        throw new Error('Firebase initialization failed. Check serviceAccountKey.json.');
    }

    onProgress(`🔗 Connected to Firestore. Preparing batch upload of ${matches.length} records...`);

    const COLLECTION = 'vfootball_results';
    const batchSize = 400; // Firestore max per batch is 500, we stay under
    let uploaded = 0;
    let skipped = 0;

    // Chunk the matches into batches
    for (let i = 0; i < matches.length; i += batchSize) {
        const chunk = matches.slice(i, i + batchSize);
        const batch = db.batch();

        for (const match of chunk) {
            if (!match.gameId || !match.league) {
                console.warn('[Firebase] ⚠️ Skipping match with missing gameId or league:', match);
                skipped++;
                continue;
            }

            // Sanitize league name for use as part of a doc ID (replace spaces/slashes)
            const leagueSafe = match.league.replace(/[^a-zA-Z0-9_-]/g, '_');
            const docId = `${match.gameId}_${leagueSafe}`;
            const docRef = db.collection(COLLECTION).doc(docId);

            // merge: true means if the document exists, only changed fields update
            batch.set(docRef, {
                ...match,
                uploadedAt: admin.firestore.FieldValue.serverTimestamp(),
            }, { merge: true });

            uploaded++;
        }

        await batch.commit();
        onProgress(`📤 Committed batch ${Math.ceil((i + 1) / batchSize)} — ${Math.min(i + batchSize, matches.length)}/${matches.length} records pushed...`);
    }

    return { uploaded, skipped };
}

module.exports = { uploadMatchesToFirebase, initFirebase };
