const TelegramBot = require('node-telegram-bot-api');
const fs = require('fs');
const path = require('path');
const { TelegramUser, SystemSettings, Transaction } = require('./db_init');
const { callPredictionAI, parseAIJson, generateSmartPrompt, calculateImpliedProbability } = require('./prediction_ai');
const { computeTeamForm, computeH2HForm } = require('./db_reader');
const { sendOtpEmail } = require('./mailer');
const { initiateSquadPayment } = require('./squad');
require('dotenv').config();

// ── Admin Authority ───────────────────────────────────────────────────────────
const ADMINS_FILE = path.join(__dirname, 'admins.json');
const SUPER_ADMIN_ID = process.env.SUPER_ADMIN_ID || '5129381';

function getSubAdmins() {
    try {
        const raw = fs.readFileSync(ADMINS_FILE, 'utf8');
        return JSON.parse(raw);
    } catch { return []; }
}

function saveSubAdmins(list) {
    fs.writeFileSync(ADMINS_FILE, JSON.stringify(list, null, 2));
}

function isAdmin(chatId) {
    const id = chatId.toString();
    if (id === SUPER_ADMIN_ID) return true;
    return getSubAdmins().includes(id);
}

function isSuperAdmin(chatId) {
    return chatId.toString() === SUPER_ADMIN_ID;
}

const token = process.env.TELEGRAM_BOT_TOKEN;
let bot = null;
let systemGlobals = null;

if (token) {
    bot = new TelegramBot(token, { polling: true });
    console.log('[TelegramBot] 🤖 Bot connected and polling initialized.');
} else {
    console.warn('[TelegramBot] ⚠️ TELEGRAM_BOT_TOKEN missing. Bot will not start.');
}

// Ensure global settings exist
async function getSettings() {
    let settings = await SystemSettings.findById('global_config');
    if (!settings) {
        settings = await SystemSettings.create({ _id: 'global_config' });
    }
    return settings;
}

// Auth utility ensures user exists in db
async function authenticateUser(msg, refId = null) {
    const chatId = msg.chat.id.toString();
    const username = msg.from.username || msg.from.first_name || 'User';
    
    let user = await TelegramUser.findById(chatId);
    let isNew = false;
    if (!user) {
        user = await TelegramUser.create({
            _id: chatId,
            username,
            pointsBalance: 0,
            subscriptionTier: 'none',
            referredBy: refId,
            botState: 'awaiting_email',
            isEmailVerified: false
        });
        isNew = true;
    } else if (!user.isEmailVerified && user.botState === 'none') {
        // Legacy user who hasn't verified email yet
        user.botState = 'awaiting_email';
        await user.save();
    }
    return { user, isNew };
}

// Generate the Main Menu Inline Keyboard
function getMainMenu(user) {
    const webAppUrl = process.env.MINI_APP_URL || 'https://vfootball-dashboard.web.app'; // Placeholder
    return {
        reply_markup: {
            inline_keyboard: [
                [{ text: '📱 Open vFootball App', web_app: { url: webAppUrl } }],
                [
                    { text: '🔮 AI Predict', callback_data: 'predict_ai' },
                    { text: '⚡ Normal Predict', callback_data: 'predict_normal' }
                ],
                [
                    { text: '💳 Buy Points', callback_data: 'buy_points' },
                    { text: '🤝 Invite & Earn', callback_data: 'referral_system' }
                ],
                [
                    { text: '🎁 Claim Daily Bonus', callback_data: 'claim_bonus' }
                ],
                [
                    { text: `💰 Balance: ${user.pointsBalance} PTS`, callback_data: 'balance' },
                    { text: '💎 PRO', callback_data: 'subscribe' }
                ]
            ]
        }
    };
}

// Generate the Terms of Service Disclaimer
function getTermsDisclaimer() {
    const text = `⚠️ **DISCLAIMER & TERMS OF SERVICE** ⚠️\n\n` +
                 `vFootball AI provides statistical and AI-driven predictions for Virtual Football games (including platforms like SportyBet Virtuals, Bet9ja League, etc.).\n\n` +
                 `➤ *Our predictions do NOT guarantee winning outcomes.*\n` +
                 `➤ *Virtual sports are algorithmically generated by operators, and results can be unpredictable.*\n` +
                 `➤ *vFootball AI is a tool for statistical estimation, not financial advice.*\n` +
                 `➤ *Please stake responsibly and strictly within your limits.*\n\n` +
                 `By clicking **Accept**, you acknowledge these risks and agree to use our AI tools responsibly.`;
    const keyboard = {
        inline_keyboard: [
            [{ text: '✅ I Accept & Agree', callback_data: 'accept_terms' }],
            [{ text: '❌ Decline (Exit)', callback_data: 'decline_terms' }]
        ]
    };
    return { text, keyboard };
}

if (bot) {
    // Regex matches /start OR /start <ref_id>
    bot.onText(/\/start(?:\s+(.+))?/, async (msg, match) => {
        const refId = match[1] || null;
        const { user, isNew } = await authenticateUser(msg, refId);
        
        // Handle Referral Logic if it's a completely new user joining via a link
        if (isNew && refId && refId !== user._id) {
            try {
                const parent = await TelegramUser.findById(refId);
                const settings = await getSettings();
                if (parent && settings.referralRewardPoints > 0) {
                    parent.pointsBalance += settings.referralRewardPoints;
                    parent.referralsCount += 1;
                    parent.totalReferralEarnings += settings.referralRewardPoints;
                    await parent.save();
                    
                    bot.sendMessage(parent._id, `🎉 **Referral Success!**\nSomeone just joined using your link.\nYou earned +${settings.referralRewardPoints} PTS!`);
                }
            } catch (err) {
                console.error('[Referral Error]', err);
            }
        }
        
        if (!user.isEmailVerified) {
            user.botState = 'awaiting_email';
            await user.save();
            return bot.sendMessage(msg.chat.id, `🔒 **Account Verification Required**\n\nPlease enter your Email Address to register and secure your account.`, { parse_mode: 'Markdown' });
        }

        if (!user.hasAcceptedTerms) {
            const terms = getTermsDisclaimer();
            bot.sendMessage(msg.chat.id, terms.text, { parse_mode: 'Markdown', reply_markup: terms.keyboard });
        } else {
            bot.sendMessage(msg.chat.id, `👋 Welcome back to vFootball AI, ${user.username}!\n\nGet live AI-powered predictions for virtual football matches right here.\n\nUse the menu below to get started.`, getMainMenu(user));
        }
    });

    // Handle generic text messages (for Email & OTP states)
    bot.on('message', async (msg) => {
        if (!msg.text || msg.text.startsWith('/')) return; // Ignore commands

        const { user } = await authenticateUser(msg);
        const chatId = msg.chat.id;

        if (user.botState === 'awaiting_email') {
            const emailRegex = /^[^\s@]+@[^\s@]+\.[^\s@]+$/;
            const email = msg.text.trim();
            
            if (!emailRegex.test(email)) {
                return bot.sendMessage(chatId, "❌ Invalid email format. Please enter a valid email address.");
            }

            bot.sendMessage(chatId, "⏳ Sending verification code...");
            const otpCode = Math.floor(100000 + Math.random() * 900000).toString(); // 6 digits
            const expires = new Date(Date.now() + 10 * 60000); // 10 mins

            const emailSent = await sendOtpEmail(email, otpCode);
            if (emailSent) {
                user.email = email;
                user.otpCode = otpCode;
                user.otpExpiresAt = expires;
                user.botState = 'awaiting_otp';
                await user.save();
                bot.sendMessage(chatId, `✅ We've sent a 6-digit verification code to **${email}**.\n\nPlease reply with the code to verify your account.`, { parse_mode: 'Markdown' });
            } else {
                bot.sendMessage(chatId, "❌ Failed to send email. Please check the address or try again later.");
            }
        } 
        else if (user.botState === 'awaiting_otp') {
            const code = msg.text.trim();
            
            if (user.otpCode !== code || new Date() > user.otpExpiresAt) {
                return bot.sendMessage(chatId, "❌ Invalid or expired verification code. Please try again.\n\n(Type /start to restart and enter a different email)");
            }

            // OTP valid
            user.isEmailVerified = true;
            user.botState = 'none';
            user.otpCode = null;
            await user.save();

            bot.sendMessage(chatId, "🎉 **Email Verified Successfully!**", { parse_mode: 'Markdown' });

            // Proceed to terms Disclaimer
            if (!user.hasAcceptedTerms) {
                const terms = getTermsDisclaimer();
                bot.sendMessage(chatId, terms.text, { parse_mode: 'Markdown', reply_markup: terms.keyboard });
            } else {
                bot.sendMessage(chatId, `👋 Welcome to vFootball AI, ${user.username}!\n\nUse the menu below to get started.`, getMainMenu(user));
            }
        }
    });

    // Callback Query Handler for Inline Buttons
    bot.on('callback_query', async (query) => {
        const chatId = query.message.chat.id;
        const msgId = query.message.message_id;
        const action = query.data;
        const { user } = await authenticateUser(query.message);
        const settings = await getSettings();

        if (!user.isEmailVerified) {
            return bot.answerCallbackQuery(query.id, { text: "⚠️ You must verify your email address to continue. Send /start", show_alert: true });
        }

        if (!user.hasAcceptedTerms && action !== 'accept_terms' && action !== 'decline_terms') {
            await bot.answerCallbackQuery(query.id, { text: "⚠️ You must accept the Terms of Service to continue.", show_alert: true });
            const terms = getTermsDisclaimer();
            return bot.sendMessage(chatId, terms.text, { parse_mode: 'Markdown', reply_markup: terms.keyboard });
        }

        // Check if user has active subscription
        const hasActiveSub = user.subscriptionTier !== 'none' && user.subscriptionExpiry && new Date() < user.subscriptionExpiry;

        try {
            if (action === 'accept_terms') {
                user.hasAcceptedTerms = true;
                await user.save();
                bot.answerCallbackQuery(query.id, { text: "✅ Terms Accepted." });
                bot.editMessageText(`👋 Welcome to vFootball AI, ${user.username}!\n\nGet live AI-powered predictions for virtual football matches right here.\n\nUse the menu below to get started.`, { chat_id: chatId, message_id: msgId, reply_markup: getMainMenu(user).reply_markup });
            } else if (action === 'decline_terms') {
                bot.answerCallbackQuery(query.id);
                bot.editMessageText("❌ You have declined the Terms. The bot will not provide predictions unless you accept.", { chat_id: chatId, message_id: msgId });
            } else if (action === 'predict_ai' || action === 'predict_normal') {
                // Read cost dynamically from SystemSettings so /admin cost commands take effect
                const cost = action === 'predict_ai' ? settings.aiPredictionCost : settings.normalPredictionCost;
                
                if (!hasActiveSub && user.pointsBalance < cost) {
                    await bot.answerCallbackQuery(query.id, { text: `❌ Not enough points! Need ${cost} points for this 8-Match batch.`, show_alert: true });
                    return bot.sendMessage(chatId, `You need **${cost} points** for a Batch Oracle. Buy points or subscribe!`, { parse_mode: 'Markdown', ...getMainMenu(user) });
                }

                if (!hasActiveSub) {
                    user.pointsBalance -= cost;
                    user.totalPredictionsRequested += 1;
                    await user.save();
                }

                // Normal & AI Prediction extraction based on Live State
                bot.answerCallbackQuery(query.id, { text: `Searching live games...` });
                
                const typeName = action === 'predict_ai' ? '🤖 AI Deep' : '⚡ Normal';
                let tipText = "No live virtual games available right now for prediction. Try again later!";
                
                if (systemGlobals && systemGlobals.globalData && Array.isArray(systemGlobals.globalData) && systemGlobals.globalData.length > 0) {
                    const validGroups = systemGlobals.globalData.filter(g => g.matches && g.matches.length > 0);
                    
                    if (validGroups.length > 0) {
                        let matchBatch = [];
                        for (let i = 0; i < 8; i++) {
                            const group = validGroups[Math.floor(Math.random() * validGroups.length)];
                            const matchObj = group.matches[Math.floor(Math.random() * group.matches.length)];
                            matchBatch.push({ league: group.league, ...matchObj });
                        }

                        if (matchBatch.length > 0) {
                            bot.sendMessage(chatId, `🔍 Found ${matchBatch.length} live games. Running batch computations...`);
                            
                            // Enhance with form
                            let augmentedBatch = [];
                            for (let mb of matchBatch) {
                                const home = mb.home || (mb.match ? mb.match.split(' vs ')[0].trim() : 'Home');
                                const away = mb.away || (mb.match ? mb.match.split(' vs ')[1].trim() : 'Away');
                                const [homeFormData, awayFormData, h2hFormData] = await Promise.all([
                                    computeTeamForm(mb.league, home, 10),
                                    computeTeamForm(mb.league, away, 10),
                                    computeH2HForm(mb.league, home, away, 10)
                                ]);
                                
                                augmentedBatch.push({
                                    league: mb.league,
                                    home: home,
                                    away: away,
                                    match: mb.match || `${home} vs ${away}`,
                                    oddsStr: mb.score, // The scraper stores odds in 'score' ironically
                                    homeForm: homeFormData.form || 'Unknown',
                                    awayForm: awayFormData.form || 'Unknown',
                                    h2hForm: h2hFormData.form || 'Unknown'
                                });
                            }

                            if (action === 'predict_ai') {
                                try {
                                    const { generateBatchSmartPrompt, callPredictionAI, parseAIJson } = require('./prediction_ai');
                                    const prompt = generateBatchSmartPrompt(augmentedBatch);
                                    
                                    const aiResult = await callPredictionAI(prompt);
                                    const parsedArray = parseAIJson(aiResult.content);

                                    tipText = `🔍 **${typeName} Batch Output**\n\n`;
                                    if (Array.isArray(parsedArray)) {
                                        parsedArray.forEach(p => {
                                             tipText += `🔹 *${p.match}*\nTip: ${p.tip} | Conf: ${p.confidence}\n\n`;
                                        });
                                    } else {
                                        tipText += "Failed to parse batch JSON.";
                                    }
                                } catch (aiError) {
                                    console.error('[Bot AI Error]', aiError);
                                    tipText = "⚠️ The AI Core is currently busy or down. Please try again or use Normal predict.";
                                }
                            } else {
                                const { calculateImpliedProbability } = require('./prediction_ai');
                                tipText = `⚡ **${typeName} Fast Batch Output**\n\n`;
                                
                                for (let bt of augmentedBatch) {
                                    const probs = calculateImpliedProbability(bt.oddsStr);
                                    let fastTip = "Home or Away Win (12)";
                                    let conf = "75%";
                                    
                                    if (probs.valid) {
                                        const homeWantsToWin = probs.home > 50;
                                        const awayWantsToWin = probs.away > 50;
                                        const homeHasGoodForm = bt.homeForm.includes('W') && !bt.homeForm.endsWith('LL');
                                        const awayHasGoodForm = bt.awayForm.includes('W') && !bt.awayForm.endsWith('LL');

                                        if (homeWantsToWin && homeHasGoodForm) { fastTip = "Home Win (1) or 1X"; conf = `${probs.home + 15}%`; }
                                        else if (awayWantsToWin && awayHasGoodForm) { fastTip = "Away Win (2) or X2"; conf = `${probs.away + 15}%`; }
                                        else if ((homeWantsToWin && !homeHasGoodForm) || (awayWantsToWin && !awayHasGoodForm)) {
                                            fastTip = "Over 1.5 Goals & GG (Trap avoided)"; conf = `88%`;
                                        } else { fastTip = "Under 3.5 Goals or DC"; conf = "80%"; }
                                    }
                                    tipText += `🔹 *${bt.match}*\nTip: ${fastTip} | Conf: ${conf}\n\n`;
                                }
                            }
                        }
                    }
                }

                bot.sendMessage(chatId, tipText, { parse_mode: 'Markdown' });
            
            } else if (action === 'buy_points') {
                bot.answerCallbackQuery(query.id);
                // Prompt user with point packages (can link to Squad API or send Telegram Stars invoice here)
                const pointPackages = {
                    inline_keyboard: [
                        [{ text: '⭐ 100 Points - 100 Stars', callback_data: 'purchase_stars_100' }],
                        [{ text: '⭐ 500 Points - 450 Stars', callback_data: 'purchase_stars_500' }],
                        [{ text: '💳 500 Points - ₦2500 (Squad)', callback_data: 'purchase_squad_500' }],
                        [{ text: '🔙 Back', callback_data: 'main_menu' }]
                    ]
                };
                bot.editMessageText(`Choose a package to buy points.`, { chat_id: chatId, message_id: msgId, reply_markup: pointPackages });
            
            } else if (action === 'purchase_stars_100' || action === 'purchase_stars_500') {
                bot.answerCallbackQuery(query.id);
                const is100 = action === 'purchase_stars_100';
                const pkgPoints = is100 ? 100 : 500;
                const pkgPrices = [ { label: 'Points', amount: is100 ? 100 : 450 } ];
                
                bot.sendInvoice(
                    chatId,
                    `vFootball ${pkgPoints} Points Pack`,
                    `Purchase ${pkgPoints} points to use for AI Live Matches and Normal Predictions.`,
                    `stars_points_${pkgPoints}_${Date.now()}`,
                    '', // Provider token must be empty for Telegram Stars
                    'XTR', // Telegram Stars Currency
                    pkgPrices
                );
            } else if (action === 'purchase_squad_500') {
                bot.answerCallbackQuery(query.id, { text: "Generating secure checkout link..." });
                try {
                    const checkoutUrl = await initiateSquadPayment({
                        email: user.email,
                        amount: 250000, // 2500 NGN in Kobo
                        telegramId: user._id,
                        type: 'points',
                        points: 500
                    });
                    
                    bot.editMessageText(`💳 **Squad Checkout Ready**\n\nClick below to securely purchase 500 Points for ₦2,500. Your account will be credited automatically.`, { 
                        chat_id: chatId, 
                        message_id: msgId, 
                        parse_mode: 'Markdown',
                        reply_markup: {
                            inline_keyboard: [
                                [{ text: '➡️ Pay via Squad', url: checkoutUrl }],
                                [{ text: '🔙 Back', callback_data: 'buy_points' }]
                            ]
                        }
                    });
                } catch (err) {
                    bot.sendMessage(chatId, "⚠️ Failed to generate Squad payment link. Please try again later.");
                }
            } else if (action === 'balance') {
                bot.answerCallbackQuery(query.id, { text: `💰 Balance: ${user.pointsBalance} Points\n💎 Sub: ${user.subscriptionTier.toUpperCase()}`, show_alert: true });
            
            } else if (action === 'subscribe') {
                bot.answerCallbackQuery(query.id);
                const subPackages = {
                    inline_keyboard: [
                        [{ text: '⭐ 1 Month PRO - 500 Stars', callback_data: 'purchase_stars_pro' }],
                        [{ text: '💳 1 Month PRO - ₦2500 (Squad)', callback_data: 'purchase_squad_pro' }],
                        [{ text: '🔙 Back', callback_data: 'main_menu' }]
                    ]
                };
                bot.editMessageText(`Upgrade to 💎 PRO Subscription.\nGain unlimited AI predictions and exclusive insights for 30 days!`, { chat_id: chatId, message_id: msgId, reply_markup: subPackages });

            } else if (action === 'purchase_stars_pro') {
                bot.answerCallbackQuery(query.id);
                bot.sendInvoice(
                    chatId,
                    `vFootball 💎 PRO Subscription`,
                    `Unlock unlimited AI Predictions for 30 Days.`,
                    `stars_pro_${Date.now()}`,
                    '', // Empty for stars
                    'XTR',
                    [{ label: '1 Month PRO', amount: 500 }]
                );
            } else if (action === 'purchase_squad_pro') {
                bot.answerCallbackQuery(query.id, { text: "Generating secure PRO checkout link..." });
                try {
                    const checkoutUrl = await initiateSquadPayment({
                        email: user.email,
                        amount: 250000, // 2500 NGN in Kobo
                        telegramId: user._id,
                        type: 'pro'
                    });
                    
                    bot.editMessageText(`💎 **PRO Subscription Checkout**\n\nClick below to activate 1 Month PRO for ₦2,500. Your account will automatically upgrade.`, { 
                        chat_id: chatId, 
                        message_id: msgId, 
                        parse_mode: 'Markdown',
                        reply_markup: {
                            inline_keyboard: [
                                [{ text: '➡️ Pay via Squad', url: checkoutUrl }],
                                [{ text: '🔙 Back', callback_data: 'subscribe' }]
                            ]
                        }
                    });
                } catch (err) {
                    bot.sendMessage(chatId, "⚠️ Failed to generate Squad PRO link. Please try again later.");
                }
            } else if (action === 'referral_system') {
                bot.answerCallbackQuery(query.id);
                try {
                    const botDetails = await bot.getMe();
                    const refLink = `https://t.me/${botDetails.username}?start=${chatId}`;
                    const settings = await getSettings();
                    
                    const msgText = `🤝 **Invite Friends & Earn Points!**\n\n` +
                                    `Earn **${settings.referralRewardPoints} Points** for every new person who joins using your link.\n\n` +
                                    `Your Referral Link:\n\`${refLink}\`\n\n` +
                                    `👥 Total Referrals: ${user.referralsCount}\n` +
                                    `🎁 Earnings: ${user.totalReferralEarnings} PTS`;
                    
                    bot.editMessageText(msgText, { 
                        chat_id: chatId, 
                        message_id: msgId, 
                        reply_markup: {
                            inline_keyboard: [[{ text: '🔙 Back', callback_data: 'main_menu' }]]
                        },
                        parse_mode: 'Markdown'
                    });
                } catch (e) {
                    console.error("Ref error", e);
                }
            } else if (action === 'claim_bonus') {
                const now = new Date();
                if (user.lastBonusClaimDate) {
                    const hoursSinceLastClaim = Math.abs(now - user.lastBonusClaimDate) / 36e5;
                    if (hoursSinceLastClaim < 24) {
                        const hoursLeft = Math.ceil(24 - hoursSinceLastClaim);
                        return bot.answerCallbackQuery(query.id, { 
                            text: `⏳ You already claimed your bonus today! Come back in ${hoursLeft} hours.`, 
                            show_alert: true 
                        });
                    }
                }
                
                // Grant 10 points
                user.pointsBalance += 10;
                user.lastBonusClaimDate = now;
                await user.save();
                
                bot.answerCallbackQuery(query.id, { text: '🎉 10 Points Daily Bonus Claimed!', show_alert: true });
                bot.editMessageText(`👋 Welcome to vFootball AI, ${user.username}!\n\nGet live AI-powered predictions for virtual football matches right here.\n\nUse the menu below to get started.`, { chat_id: chatId, message_id: msgId, reply_markup: getMainMenu(user).reply_markup });
            } else if (action === 'main_menu') {
                bot.answerCallbackQuery(query.id);
                bot.editMessageText(`Welcome to vFootball AI!`, { chat_id: chatId, message_id: msgId, reply_markup: getMainMenu(user).reply_markup });
            }

        } catch (err) {
            console.error('[Bot Error]', err);
            bot.answerCallbackQuery(query.id, { text: 'An error occurred. Please try again later.', show_alert: true });
        }
    });

    // Handle Telegram Stars Pre-Checkout
    bot.on('pre_checkout_query', (query) => {
        // We can validate if user is allowed to buy, stock available, etc.
        // For digital goods (points), we generally always approve.
        bot.answerPreCheckoutQuery(query.id, true);
    });

    // Handle Telegram Stars Successful Payment
    bot.on('successful_payment', async (msg) => {
        const chatId = msg.chat.id.toString();
        const payload = msg.successful_payment.invoice_payload;
        
        let pointsToAdd = 0;
        if (payload.includes('stars_points_100')) pointsToAdd = 100;
        if (payload.includes('stars_points_500')) pointsToAdd = 500;
        
        if (pointsToAdd > 0) {
            const user = await TelegramUser.findById(chatId);
            if (user) {
                user.pointsBalance += pointsToAdd;
                await user.save();
                
                // Log transaction
                const { Transaction } = require('./db_init');
                await Transaction.create({
                    _id: msg.successful_payment.telegram_payment_charge_id,
                    telegramId: chatId,
                    amount: pointsToAdd,
                    currency: 'STARS',
                    method: 'telegram_stars',
                    status: 'completed',
                    type: 'points',
                    itemBought: `${pointsToAdd} Points Pack`
                });

                bot.sendMessage(chatId, `✅ Payment Successful! You bought ${pointsToAdd} points.\n\nYour new balance is ${user.pointsBalance} PTS.`, getMainMenu(user));
            }
        } else if (payload.includes('stars_pro_')) {
            const user = await TelegramUser.findById(chatId);
            if (user) {
                user.subscriptionTier = 'pro';
                user.subscriptionExpiry = new Date(Date.now() + 30 * 24 * 60 * 60 * 1000); // 30 days
                await user.save();

                const { Transaction } = require('./db_init');
                await Transaction.create({
                    _id: msg.successful_payment.telegram_payment_charge_id,
                    telegramId: chatId,
                    amount: 500,
                    currency: 'STARS',
                    method: 'telegram_stars',
                    status: 'completed',
                    type: 'subscription',
                    itemBought: `1 Month PRO Subscription`
                });

                bot.sendMessage(chatId, `🎉 Successfully Upgraded to 💎 PRO!\nYou now have unlimited AI predictive access for 30 days.`, getMainMenu(user));
            }
        }
    });

    bot.on('polling_error', (error) => {
        console.warn('[TelegramBot Polling Error]', error.message);
    });

    // ── /admin command router ─────────────────────────────────────────────────
    // Usage:
    //   /admin cost normal 8           - set normal prediction cost
    //   /admin cost ai 5               - set AI prediction cost
    //   /admin cost referral 15        - set referral reward points
    //   /admin broadcast Hello all!    - send message to every verified user
    //   /admin promote 123456789       - add sub-admin (super admin only)
    //   /admin demote  123456789       - remove sub-admin (super admin only)
    //   /admin grant 123456789 500     - manually credit a user points
    //   /admin revoke 123456789        - set user points balance to 0
    //   /admin stats                   - show platform statistics
    //   /admin help                    - show this reference
    bot.onText(/^\/admin(?:\s+(.+))?/, async (msg, match) => {
        const chatId = msg.chat.id.toString();
        const args = (match[1] || '').trim();

        if (!isAdmin(chatId)) {
            return bot.sendMessage(chatId, '⛔ Access denied. Admin privileges required.');
        }

        const parts = args.split(/\s+/);
        const cmd = parts[0]?.toLowerCase();

        try {
            // ── /admin help ──────────────────────────────────────────────────
            if (!cmd || cmd === 'help') {
                const isSA = isSuperAdmin(chatId);
                return bot.sendMessage(chatId,
                    `🔐 *vFootball Admin Panel*\n\n` +
                    `*Cost Controls:*\n` +
                    `\`/admin cost normal <pts>\` — Normal batch cost\n` +
                    `\`/admin cost ai <pts>\` — AI batch cost\n` +
                    `\`/admin cost referral <pts>\` — Referral reward\n\n` +
                    `*Users:*\n` +
                    `\`/admin grant <ID> <pts>\` — Credit user\n` +
                    `\`/admin revoke <ID>\` — Zero out user balance\n\n` +
                    `*Broadcast:*\n` +
                    `\`/admin broadcast <message>\` — Message all users\n\n` +
                    `*Stats:*\n` +
                    `\`/admin stats\` — Platform summary\n` +
                    (isSA ? `\n*Super Admin Only:*\n\`/admin promote <ID>\`\n\`/admin demote <ID>\`` : ''),
                    { parse_mode: 'Markdown' }
                );
            }

            // ── /admin cost <type> <value> ───────────────────────────────────
            if (cmd === 'cost') {
                const type  = parts[1]?.toLowerCase();
                const value = parseInt(parts[2]);
                if (!type || isNaN(value) || value < 1) {
                    return bot.sendMessage(chatId, '❌ Usage: `/admin cost normal|ai|referral <number>`', { parse_mode: 'Markdown' });
                }
                const settings = await getSettings();
                if (type === 'normal')   settings.normalPredictionCost   = value;
                else if (type === 'ai')  settings.aiPredictionCost        = value;
                else if (type === 'referral') settings.referralRewardPoints = value;
                else return bot.sendMessage(chatId, '❌ Unknown cost type. Use: normal | ai | referral');
                settings.updatedAt = new Date();
                await settings.save();
                return bot.sendMessage(chatId, `✅ *${type.toUpperCase()} cost* updated to *${value} points*.`, { parse_mode: 'Markdown' });
            }

            // ── /admin broadcast <message> ───────────────────────────────────
            if (cmd === 'broadcast') {
                const message = parts.slice(1).join(' ');
                if (!message) return bot.sendMessage(chatId, '❌ Usage: `/admin broadcast <message>`', { parse_mode: 'Markdown' });

                bot.sendMessage(chatId, `📡 Starting broadcast to all verified users...`);
                const users = await TelegramUser.find({ isEmailVerified: true });
                let sent = 0, failed = 0;
                for (const u of users) {
                    try {
                        await bot.sendMessage(u._id, `📢 *vFootball Announcement:*\n\n${message}`, { parse_mode: 'Markdown' });
                        sent++;
                        // Throttle to avoid Telegram flood limits
                        await new Promise(r => setTimeout(r, 100));
                    } catch { failed++; }
                }
                return bot.sendMessage(chatId, `✅ Broadcast complete.\n• Delivered: ${sent}\n• Failed: ${failed}`);
            }

            // ── /admin promote <id>  (super admin only) ──────────────────────
            if (cmd === 'promote') {
                if (!isSuperAdmin(chatId)) return bot.sendMessage(chatId, '⛔ Only the super admin can promote users.');
                const targetId = parts[1];
                if (!targetId) return bot.sendMessage(chatId, '❌ Usage: `/admin promote <telegramId>`', { parse_mode: 'Markdown' });
                const admins = getSubAdmins();
                if (admins.includes(targetId)) return bot.sendMessage(chatId, `⚠️ ${targetId} is already a sub-admin.`);
                admins.push(targetId);
                saveSubAdmins(admins);
                bot.sendMessage(targetId, `🔑 You have been promoted to *vFootball Admin* by the Super Admin.`, { parse_mode: 'Markdown' }).catch(() => {});
                return bot.sendMessage(chatId, `✅ *${targetId}* promoted to admin and saved to \`admins.json\`.`, { parse_mode: 'Markdown' });
            }

            // ── /admin demote <id>  (super admin only) ───────────────────────
            if (cmd === 'demote') {
                if (!isSuperAdmin(chatId)) return bot.sendMessage(chatId, '⛔ Only the super admin can demote admins.');
                const targetId = parts[1];
                if (!targetId) return bot.sendMessage(chatId, '❌ Usage: `/admin demote <telegramId>`', { parse_mode: 'Markdown' });
                const admins = getSubAdmins().filter(id => id !== targetId);
                saveSubAdmins(admins);
                return bot.sendMessage(chatId, `✅ *${targetId}* has been demoted.`, { parse_mode: 'Markdown' });
            }

            // ── /admin grant <id> <points> ───────────────────────────────────
            if (cmd === 'grant') {
                const targetId = parts[1];
                const amount   = parseInt(parts[2]);
                if (!targetId || isNaN(amount) || amount < 1) {
                    return bot.sendMessage(chatId, '❌ Usage: `/admin grant <telegramId> <points>`', { parse_mode: 'Markdown' });
                }
                const targetUser = await TelegramUser.findById(targetId);
                if (!targetUser) return bot.sendMessage(chatId, `❌ User \`${targetId}\` not found in database.`, { parse_mode: 'Markdown' });
                targetUser.pointsBalance += amount;
                await targetUser.save();
                bot.sendMessage(targetId, `🎁 An admin has credited you *+${amount} Points*!\nYour new balance: *${targetUser.pointsBalance} PTS*`, { parse_mode: 'Markdown' }).catch(() => {});
                return bot.sendMessage(chatId, `✅ Granted *${amount} pts* to \`${targetId}\`. New balance: *${targetUser.pointsBalance} PTS*.`, { parse_mode: 'Markdown' });
            }

            // ── /admin revoke <id> ───────────────────────────────────────────
            if (cmd === 'revoke') {
                const targetId = parts[1];
                if (!targetId) return bot.sendMessage(chatId, '❌ Usage: `/admin revoke <telegramId>`', { parse_mode: 'Markdown' });
                const targetUser = await TelegramUser.findById(targetId);
                if (!targetUser) return bot.sendMessage(chatId, `❌ User \`${targetId}\` not found.`, { parse_mode: 'Markdown' });
                targetUser.pointsBalance = 0;
                await targetUser.save();
                return bot.sendMessage(chatId, `✅ Balance for \`${targetId}\` zeroed out.`, { parse_mode: 'Markdown' });
            }

            // ── /admin stats ─────────────────────────────────────────────────
            if (cmd === 'stats') {
                const totalUsers     = await TelegramUser.countDocuments();
                const verifiedUsers  = await TelegramUser.countDocuments({ isEmailVerified: true });
                const proUsers       = await TelegramUser.countDocuments({ subscriptionTier: 'pro', subscriptionExpiry: { $gt: new Date() } });
                const totalTx        = await Transaction.countDocuments({ status: 'completed' });
                const settings       = await getSettings();
                const admins         = getSubAdmins();

                return bot.sendMessage(chatId,
                    `📊 *vFootball Platform Stats*\n\n` +
                    `👥 Total Users: *${totalUsers}*\n` +
                    `✅ Verified: *${verifiedUsers}*\n` +
                    `💎 Active PRO: *${proUsers}*\n` +
                    `💳 Transactions: *${totalTx}*\n\n` +
                    `*Current Costs:*\n` +
                    `⚡ Normal: *${settings.normalPredictionCost} pts*\n` +
                    `🤖 AI: *${settings.aiPredictionCost} pts*\n` +
                    `🤝 Referral: *${settings.referralRewardPoints} pts*\n\n` +
                    `🔑 Sub-Admins: ${admins.length > 0 ? admins.join(', ') : 'None'}`,
                    { parse_mode: 'Markdown' }
                );
            }

            bot.sendMessage(chatId, `❓ Unknown admin command. Send \`/admin help\` for a full list.`, { parse_mode: 'Markdown' });

        } catch (err) {
            console.error('[Admin Command Error]', err);
            bot.sendMessage(chatId, `❌ Command failed: ${err.message}`);
        }
    });
}

function startBot(globals) {
    systemGlobals = globals;
    console.log('[TelegramBot] Bridge initialized with global state context.');
}

module.exports = {
    bot,
    startBot
};
